version: '3.8'

services:
  stat-service:
    build: ./stat-svc/service
    depends_on:
      stat-db:
        condition: service_healthy
    environment:
      - DB_NAME=ewm-stat
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=stat-db
      - DB_PORT=5432
    ports:
      - "9090:9090"

  stat-db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_stat_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-stat
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  main-service:
    build: ./main-svc
    depends_on:
      main-db:
        condition: service_healthy
      stat-service:
        condition: service_started

    environment:
      - DB_NAME=ewm-main
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - DB_HOST=main-db
      - DB_PORT=5432
      - STAT_SVC_URL=http://stat-service:9090
    ports:
      - "8080:8080"

  main-db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - "5430:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

volumes:
  postgres_stat_data:
  postgres_main_data:
